---
- name: Install fail2ban (RedHat).
  package:
    name: fail2ban
    state: present
    enablerepo: epel
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install fail2ban (Debian).
  package:
    name: fail2ban
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Assert for deprecated variable
  assert:
    quiet: true
    that:
      - security_fail2ban_custom_configuration_template is not defined
    fail_msg: |
      [DEPRECATION WARNING]: security_fail2ban_custom_configuration_template is deprecated
      Origin: {{ role_path }}

      Use `security_fail2ban_jail_template` instead.
  ignore_errors: true
  register: deprecated_variable

- name: Set value of deprecated_variable into correct variable
  set_fact:
    security_fail2ban_jail_template: "{{ security_fail2ban_custom_configuration_template }}"
  when:
    - deprecated_variable.failed is true

- name: Copy fail2ban jail file into place.
  template:
    src: "{{ security_fail2ban_jail_template }}"
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify:
    - reload fail2ban

- name: Copy fail2ban configuration file into place.
  template:
    src: "{{ security_fail2ban_configuration_template }}"
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_facts['os_family'] == 'Debian'
    - ansible_facts['distribution_major_version'] | int >= 12
  notify:
    - reload fail2ban

- name: Ensure fail2ban is running and enabled on boot.
  service:
    name: fail2ban
    state: started
    enabled: true
